### ISSUE TITLE
bulex vivair. Inconsistent encryption, no solution.

### ISSUE THREAD

**Issue by jodewee** [FeranyDev/gree_havc_mqtt_bridge_go#4]
I get an error when adding this reposiory to hassio;
https://github.com/FeranyDev/gree_havc_mqtt_bridge_go is not a valid add-on repository

**Comment by FeranyDev** [comment]
Yes. This is not a hasso plugin, it's a standalone program that converts gree's udp protocol to mqtt protocol.

**Comment by jodewee** [comment]
ok, got it, when i try to run it, i get this error;
{"time":"2022-10-13T09:27:06.56051058+02:00","level":"ERROR","prefix":"-","file":"encryptionService.go","line":"51","message":"[KEY] 解密失败：源数据长度必须是 16 的整数倍，当前长度为：197"}

**Comment by FeranyDev** [comment]
Are you using Gree's air conditioner.

**Comment by jodewee** [comment]
a spinoff brand from gree, bulex vivair, same as vaillant vivair

**Comment by FeranyDev** [comment]
Have you tried Gree Climate in hassio?

**Comment by jodewee** [comment]
yeah, also not working. it seems something with the encryptionkey.
also tried this one, but same issue, fails on the encryption key;
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent

**Comment by FeranyDev** [comment]
Oh, that would be an inconsistent encryption method.
The encryption used in gree is 'aes-128-ecb'.
If the encryption is not consistent we have no way to decipher its contents.

**Comment by jodewee** [comment]
ok thanks, game over i think
